### ISSUE TITLE
Add CORS support to server

### ISSUE THREAD

**Issue by modeswitch** [enmasseio/timesync#1]
`index.js` needs to return some extra headers for this to work, [here](https://github.com/enmasseio/timesync/blob/master/server/index.js#L120).

Let me know if you're willing to merge a PR for this and I'll write one up.

**Comment by josdejong** [comment]
Thanks, yes I'm sure open for contributions. 

I actually had CORS in an earlier version of the built-in http server (see this commit: https://github.com/enmasseio/timesync/commit/fcc1b7f293f2b9b42b12c20806c5ced16533a18a), but I thought it may not be a good idea to set access control to * by default.

In practice you will often already have a server (like express) and extend this with the timesync functionality (see main example). In that case, CORS can be handled by this server externally from the timesync module.

What did you exactly have in mind for CORS support?

**Comment by modeswitch** [comment]
I'm using your module to create a simple time source for other apps. The idea is that you load the app and tell it which time source to use, so apps across multiple machines will be using the same machine time. In that case, `*` is necessary because I don't know ahead of time which time source will be used.

Does that seem reasonable? The access control portion could be overridden by a CLI flag if you dont' want to have `*` by default.

**Comment by josdejong** [comment]
For your application you indeed need to set CORS to `*`, but I think it's important not to set this by default! 

I think though that there is no reason to intregrate CORS stuff in the timesync library itself, as you can easily route incoming requests first though some CORS handler and then to the timesync library, like:

```js
var express = require('express');
var timesyncServer = require('timesync/server');

// create an express app
var port = 8081;
var app = express();
app.listen(port);
console.log('Server listening at http://localhost:' + port);

// serve static index.html
app.get('/', express.static(__dirname));

// handle CORS for timesync requests
app.use('/timesync', function (req, res, next) {
  res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*');		
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, X-Requested-With');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');

  if (req.method === 'OPTIONS') {
    res.writeHead(204);
    res.end();
  } else {
    next();
  }
});

// handle timesync requests
app.use('/timesync', timesyncServer.requestHandler);
```

I agree though that it would be convenient if you could just provide a simple option like 
`createServer({cors: '*'})` and `attachServer(server, {path: ..., cors: ...})` instead of having to add this code yourself. That will be a nice addition, though I think this option `cors` should be `null` (disabled) by default.

**Comment by modeswitch** [comment]
Unfortunately, `Access-Control-Allow-Origin` needs to also be returned by the `POST` handler, so that doesn't quite work.

**Comment by josdejong** [comment]
Sure? I didn't test it but the header is added to any type of request including `POST` right?

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by Poky85** [comment]
This setup works well in Express.js.

```
import express from 'express'
import timesyncServer from 'timesync/server';
import cors from 'cors';

const app = express();
app.options('/timesync', cors());
app.post('/timesync', cors(), timesyncServer.requestHandler);
```

**Comment by josdejong** [comment]
Thanks for sharing Jiri!
