### ISSUE TITLE
Remove socket.io as a dependency

### ISSUE THREAD

**Issue by DetweilerRyan** [enmasseio/timesync#2]
Since socket.io is only used in an example and is not required to use timesync in a project, it should not be a dependency.

**Comment by josdejong** [comment]
Yes, that true. On the other hand, it's also worth something that you can run the examples right out of the box.

**Comment by DetweilerRyan** [comment]
Good point, being able to run the examples out of the box has value.  Maybe a good middle ground would be to add socket.io as a DevDependency so that socket.io will not be included in production installs.  Great work on the library, by the way.

**Comment by josdejong** [comment]
That makes sense, I've changed it.

**Comment by josdejong** [comment]
Fixed in v0.2.0
