### ISSUE TITLE
Any way to use timesync with a custom API?

### ISSUE THREAD

**Issue by pmuller** [enmasseio/timesync#41]
Hello

Your project is great. It's precisely what I'm looking for... Except for the dependency toward a JSON-RPC API.

My app is based on a GraphQL API, but my understanding is that JSON-RPC is hard-coded.

Maybe I missed something: is there an easy way to override this?

Thanks!

**Comment by josdejong** [comment]
Thanks. The basic idea if of RPC is that you send a message out with a certain `id`, and receive a response later on with that same `id`, so you can correlate the response with your original request. The RPC mechanism is independent of the underlying data transport. There are examples with HTTP requests, but also with WebSockets and WebRTC. You can indeed also use GraphQL if you like, or any protocol that allows you to get data back and forth.

**Comment by pmuller** [comment]
Basically, I'd like to simply have a `getCurrentTime` GraphQL query resolver that returns the server's current time.
While the current implementation allows using different transports, it always needs to use JSON-RPC on top of it.
Unfortunately, with GraphQL, that's not an option. I'll try to do a simple implementation of your algorithm. Thanks. :)
