### ISSUE TITLE
deprecated dependency "debug@4.2.0"

### ISSUE THREAD

**Issue by Talb2005** [enmasseio/timesync#51]
When installing timesync via npm, the following warning message is displayed:

`npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)`

**Comment by josdejong** [comment]
Thanks for reporting. Fixed now in `timesync@1.0.11`
