### ISSUE TITLE
timesync + bodyParser.json makes node.js stuck

### ISSUE THREAD

**Issue by RonenNess** [enmasseio/timesync#7]
Using timesync with bodyParser.json makes node.js freeze after few timesync requests.
I init timesync & bodyParser like this:

```
var bodyParser = require('body-parser')
app.use(bodyParser.json({type: 'application/json'}));
app.use('/timesync', timesync.requestHandler);
```

**Comment by josdejong** [comment]
Thanks for reporting. I'm not sure whether I can find time on short term to look into this. Any help would be welcome.

**Comment by SupremeTechnopriest** [comment]
Hey @RonenNess! Working on a fix for this in #8 Should be ready to merge in.  The problem was that timesync was treating express.js requests as node.js http requests.  I added in support for express.  If you can pull down #8 and confirm it works for you that would be great.

**Comment by RonenNess** [comment]
Hi @SupremeTechnopriest, thanks but I'm no longer working on that project and its long lost I think.. I was just experimenting some stuff with node. Anyway good to know you solve it, I might use timesync for future stuff 👍 

Feel free to close the ticket if you're done.

**Comment by josdejong** [comment]
Thanks for getting back Ronen, I will close this issue.
